import matplotlib.pyplot as plt
import numpy as np
from numpy.random import default_rng
from math import sqrt, cos, log, pi

vol = 100000

def sampleNormal():
    x = gen.uniform()
    y = gen.uniform()
    z = sqrt(-2 * log(x)) * cos(2*pi*y)
    
    return z

xs, ys, samples = checkDistrCont(sampleNormal, vol=vol)

plt.plot(xs, ys, color='purple')
plt.title(f"Normal distribution generated by Box-Muller method on a sample volume of {vol} ")
#plt.savefig("normal.png")
plt.show()